namespace WebShopRestService.DTO.MongoDTO
{
    public class AddressDTO
    {
        // If you're exposing the ID to the client, you can include it here
        // If the ID is generated by the database and not input by the client, you may omit it from the DTO used for creation
        

        public string Street { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }

        // Add any additional properties that you want to include in the data transfer
    }
}