name: .NET CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'  

    - name: Install SQL Server command-line tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev

    - name: Execute Database Creation Script
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -i ./WebShopRestService/Data/CreateScript.sql

    - name: Execute Database Seeding Script
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -i ./WebShopRestService/Data/InsertScript.sql

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
