name: .NET CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: WebshopDatabase
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Install MySQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client

    - name: List SQL Scripts Directory
      run: ls -la ./WebShopRestService/Data/

    - name: Wait for MySQL to become available
      run: |
        timeout=30 # Set a timeout of 90 seconds for MySQL to start
        until mysqladmin ping -h localhost --silent; do
          echo "Waiting for MySQL to start..."
          sleep 5
          timeout=$((timeout-5))
          if [ "$timeout" -le 0 ]; then
            echo "MySQL did not start in time. Exiting..."
            exit 1
          fi
        done
        echo "MySQL is up and running!"

    - name: Execute Database Creation Script
      run: |
        mysql -h localhost -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} WebshopDatabase < ./WebShopRestService/Data/CreateScript.sql

    - name: Execute Database Seeding Script
      run: |
        mysql -h localhost -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} WebshopDatabase < ./WebShopRestService/Data/InsertScript.sql

    - name: Build project
      run: dotnet build --configuration Release ./WebShopRestService

    - name: Run integration tests
      env:
        TEST_CONNECTION_STRING: "Server=localhost;Database=WebshopDatabase;User ID=root;Password=${{ secrets.MYSQL_ROOT_PASSWORD }};"
      run: dotnet test --verbosity normal ./WebShopRestService-IntegrationTest/WebShopRestService-IntegrationTest.csproj
