name: .NET CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'  # Make sure this version matches the one you use

    - name: Install SQL Server command-line tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev

    - name: Wait for SQL Server to become available
      run: |
        for i in {1..60}; do # Wait up to 5 minutes
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -Q "SELECT 1" && echo "SQL Server is up!" && break
          echo "Waiting for SQL Server to start..."
          sleep 5
        done
        if [ $i -eq 60 ]; then
          echo "SQL Server failed to start."
          exit 1
        fi

    - name: Execute Database Creation Script
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -i ./WebShopRestService/Data/CreateScript.sql

    - name: Execute Database Seeding Script
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -i ./WebShopRestService/Data/InsertScript.sql

    - name: Build project
      run: dotnet build --configuration Release ./WebShopRestService

    - name: Run integration tests
      run: dotnet test --no-build --verbosity normal ./WebShopRestService-IntegrationTest
