name: .NET CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Install SQL Server command-line tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
    - name: Wait for SQL Server to become available
      run: |
        timeout=30 # Set a timeout of 90 seconds for SQL Server to start
        until /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -Q "SELECT 1" > /dev/null 2>&1; do
          echo "Waiting for SQL Server to start..."
          sleep 5
          timeout=$((timeout-5))
          if [ "$timeout" -le 0 ]; then
            echo "SQL Server did not start in time. Fetching logs..."
            docker logs sql-server
            exit 1
          fi
        done
        echo "SQL Server is up and running!"
    - name: Execute Database Creation Script
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -i ./WebShopRestService/Data/CreateScript.sql
    - name: Execute Database Seeding Script
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P ${{ secrets.SQL_SERVER_PASSWORD }} -i ./WebShopRestService/Data/InsertScript.sql
    - name: Build project
      run: dotnet build --configuration Release ./WebShopRestService

    - name: Run integration tests
      env:
        TEST_CONNECTION_STRING: "Server=localhost,1433;Database=WebshopDatabase;User ID=SA;Password=${{ secrets.SQL_SERVER_PASSWORD }};TrustServerCertificate=True;"
      run: dotnet test --verbosity normal ./WebShopRestService-IntegrationTest/WebShopRestService-IntegrationTest.csproj

    - name: Connect to SQL Server and Retrieve Table Data
      run: |
        # Install SQL Server command-line tools
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        
        # Define SQL Server connection parameters
        server=localhost,1433
        user=SA
        password="${{ secrets.SQL_SERVER_PASSWORD }}"
        database=WebshopDatabase

        # Define a SQL query to retrieve data from all tables
        query="SELECT * FROM INFORMATION_SCHEMA.TABLES"

        # Run the SQL query and store the result in a file
        /opt/mssql-tools/bin/sqlcmd -S $server -U $user -P $password -d $database -Q "$query" -o tables_data.txt

        # Display the contents of the result file
        cat tables_data.txt
