name: External API CI

on: [push]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    # Setup .NET Core SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' 

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore WebShopRestService.sln

    # Build the solution
    - name: Build the solution
      run: dotnet build WebShopRestService.sln --no-restore --configuration Release

    # Run unit tests
    - name: Run unit tests
      run: dotnet test EksternAPIIntegrationAndUnitTest/EksternAPIIntegrationAndUnitTest.csproj --no-build --configuration Release -v n
      env:
        API_KEY: ${{ secrets.API_KEY }}  # Pass the API_KEY secret as an environment variable
